// <auto-generated />
using Brunda.Modules.Ranking.Repositories.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Funda.Assigment.Repositories.RealEstateAgentRanker.EntityFramework.Migrations
{
    [DbContext(typeof(RankingContext))]
    [Migration("20241013150353_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Funda.Assigment.Repositories.RealEstateAgentRanker.EntityFramework.Entities.ForSaleRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForSaleCount")
                        .HasColumnType("int");

                    b.Property<string>("RealEstateAgentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_ForSaleRanking");

                    b.ToTable("ForSaleRanking", "dbo");
                });

            modelBuilder.Entity("Funda.Assigment.Repositories.RealEstateAgentRanker.EntityFramework.Entities.ForSaleWithGardenRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ForSaleCount")
                        .HasColumnType("int");

                    b.Property<string>("RealEstateAgentName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_ForSaleWithGardenRanking");

                    b.ToTable("ForSaleWithGardenRanking", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
